version: '3.6'

services:
  memcached:
    image: memcached
    deploy:
      mode: replicated
      replicas: 2
  mcrouter:
    image: mcrouter
    environment:
      MCROUTER_POOL_TEST: tasks.memcached