version: '3.6'

services:
  memcached:
    image: memcached
    deploy:
      mode: replicated
      replicas: 2
  mcrouter:
    image: kevbuk/mcrouter-swarm:v0.1.0
    environment:
      MCROUTER_POOL_TEST: tasks.memcached
      MCROUTER_PORT_TEST: 11211
      MCROUTER_ROUTE: "PoolRoute|TEST"